<link rel="stylesheet" href="<?= $this->basePath('css/foro.css'); ?>" media="all" />
<h1 class="TitleSection" >Foro</h1>
<hr>
<div id="forobanner">
    <img id="AfF_1" class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame1.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame2.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame3.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame4.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame5.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame6.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame7.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame8.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame9.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame10.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame11.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame12.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame13.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame14.gif'); ?>" >
    <img class="FrameBaner" src="<?=$this->basePath('img/foroAnimation/frame15.gif'); ?>" >
</div>