<link href="<?= $this->basePath('css/jquery.gridder.min.css'); ?>" rel="stylesheet" media="all"/>
<script type="text/javascript" src="<?= $this->basePath('js/jquery.gridder.min.js'); ?>" ></script>
<div class="container">

    <ul class="gridder">
        <?php
        $iterador = 1;
        foreach ($this->imagenes as $imagen) {
            ?>
            <li class="gridder-list" data-griddercontent="#gridder-content-<?= $iterador ?>">
                <img src="<?= $this->basePath('img/basura/' . $imagen['thumbnail']) ?>" class="img-responsive" />
            </li>
            <?php
            $iterador++;
        }
        ?>
    </ul>

    <?php
    $iterador = 1;
    foreach ($this->imagenes as $imagen) {
        ?>
        <div id="gridder-content-<?= $iterador ?>" class="gridder-content">
            <div class="row">
                <div class="col-md-8">
                    <img src="<?= $this->basePath('img/basura/' . $imagen['src']) ?>" class="img-responsive img-thumbnail" alt="Responsive image" />
                </div>
                <div class="col-md-4">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Imagen <?= $iterador ?></div>
                        <div class="panel-body">                           
                            <?= $imagen['Descripcion'] ?>
                        </div>
                    </div>
                    <p></p>
                </div>
            </div>
        </div>
        <?php
        $iterador++;
    }
    ?>

</div>
