<script type="text/javascript" src="<?= $this->basePath('js/jsIndex.js') ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jsForo.js'); ?>"></script>
<div id="ContenedorCubo">
    <div id="LadoCentral">
        <div class="row">
            <div class="col-md-6">
                <div class="jumbotron">
                    <h1>Casa del Angel</h1>
                    <p>Un libro (del latín liber, libri) es una obra impresa, manuscrita o pintada en una serie de hojas de papel</p>
                    <p><a href="" class="btn btn-default btn-lg" id="btn_testiz" role="button">Learn more</a></p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/L29onMRiP3U"></iframe>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="<?= $this->basePath('img/libros.png'); ?>" alt="...">
                    <div class="caption">
                        <h3>Videos</h3>
                        <p>Un libro (del latín liber, libri) es una obra impresa, manuscrita o pintada en una serie de hojas de papel, </p>
                        <p><a href="#" class="btn btn-primary" role="button">Mostrar</a></p>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="<?= $this->basePath('img/libros.png'); ?>" alt="...">
                    <div class="caption">
                        <h3>Libros</h3>
                        <p>Un libro (del latín liber, libri) es una obra impresa, manuscrita o pintada en una serie de hojas de papel, </p>
                        <p><a href="#" class="btn btn-primary" role="button">Mostrar</a></p>
                    </div>
                </div>
            </div>


            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="<?= $this->basePath('img/libros.png'); ?>" alt="...">
                    <div class="caption">
                        <h3>Ultimos Temas</h3>
                        <p>Un libro (del latín liber, libri) es una obra impresa, manuscrita o pintada en una serie de hojas de papel, </p>

                        <p><a href="#" class="btn btn-primary" role="button">Mostrar</a></p>
                    </div>
                </div>
            </div>
        </div>



    </div>
    <div id="LadoIzquierdo" >
        <div id="targetLadoIzquierdo">

        </div>
    </div>
</div>
